<a href="https://colab.research.google.com/github/a-forty-two/EY-MarApr26/blob/main/02_10_minutes_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Introduction

When working with tabular data, such as data stored in spreadsheets or databases, pandas is the right tool for you. pandas will help you to explore, clean, and process your data.
This is a short introduction to pandas, geared mainly for new users.

we import pandas and NumPy as follows.

In [12]:
import numpy as np
import pandas as pd # TABULAR DATA -> pandas manipulates as PANEL DATAFRAME

## Object Creation

`Series` is a one-dimensional labeled array capable of holding data of any type

Creating a `Series` by passing a list of values, leting pandas create a default integer index:

In [13]:
s = pd.Series([1, 2, 4, np.nan, 9, 0])
print(s)

0    1.0
1    2.0
2    4.0
3    NaN
4    9.0
5    0.0
dtype: float64

In pandas, a data table is called a `DataFrame`. Creating a `DataFrame` by passing a NumPy array, with a datetime index and labeled columns:

In [14]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [15]:
df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns = list('ABCD'))
#df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns = ['1.2','abc','123', ' hello world'])
df

                   A         B         C         D
2013-01-01  0.418973  0.135611 -0.338661  0.874763
2013-01-02  0.372361 -0.244836  0.004223  1.479917
2013-01-03  0.058369  0.034216 -0.907333  0.775947
2013-01-04 -0.218940  0.575059  0.523515 -0.520709
2013-01-05  2.695336 -0.458856  0.931581  0.236730
2013-01-06  1.378072 -0.691832  0.347157  1.553583

Creating a `DataFrame` by passing a dict of objects that can be conversted to series-like.

In [16]:
df2 = pd.DataFrame({'A': 1.0,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo' })
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

The columns of resulting `DataFrame` have different `dtypes`

In [17]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

As you can see, the columns `A`, `B`, `C` and `D` are automaticallly tab completed. `E` and `F` are there as well the rest of the attriutes have been truncated for brevity.

## Viewing data

Here is how to view the top and bottom rows of the DataFrame.

In [18]:
df.head() # from top to bottom

                   A         B         C         D
2013-01-01  0.418973  0.135611 -0.338661  0.874763
2013-01-02  0.372361 -0.244836  0.004223  1.479917
2013-01-03  0.058369  0.034216 -0.907333  0.775947
2013-01-04 -0.218940  0.575059  0.523515 -0.520709
2013-01-05  2.695336 -0.458856  0.931581  0.236730

In [19]:
df.head(2)

                   A         B         C         D
2013-01-01  0.418973  0.135611 -0.338661  0.874763
2013-01-02  0.372361 -0.244836  0.004223  1.479917

In [20]:
df.tail(3) # bottom to top

                   A         B         C         D
2013-01-04 -0.218940  0.575059  0.523515 -0.520709
2013-01-05  2.695336 -0.458856  0.931581  0.236730
2013-01-06  1.378072 -0.691832  0.347157  1.553583

Display the index, columns.

In [21]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [22]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

`describe()` to show a quick statistic summary of your data.

In [23]:
print(dir(df)) # open anything as a directory

['A', 'B', 'C', 'D', 'T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bigquery', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_geometry', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [24]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.784028 -0.108440  0.093414  0.733372
std    1.080856  0.453613  0.655444  0.783741
min   -0.218940 -0.691832 -0.907333 -0.520709
25%    0.136867 -0.405351 -0.252940  0.371534
50%    0.395667 -0.105310  0.175690  0.825355
75%    1.138297  0.110262  0.479426  1.328628
max    2.695336  0.575059  0.931581  1.553583

Transposing your data.

In [25]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.418973    0.372361    0.058369   -0.218940    2.695336    1.378072
B    0.135611   -0.244836    0.034216    0.575059   -0.458856   -0.691832
C   -0.338661    0.004223   -0.907333    0.523515    0.931581    0.347157
D    0.874763    1.479917    0.775947   -0.520709    0.236730    1.553583

In [26]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.784028 -0.108440  0.093414  0.733372
std    1.080856  0.453613  0.655444  0.783741
min   -0.218940 -0.691832 -0.907333 -0.520709
25%    0.136867 -0.405351 -0.252940  0.371534
50%    0.395667 -0.105310  0.175690  0.825355
75%    1.138297  0.110262  0.479426  1.328628
max    2.695336  0.575059  0.931581  1.553583

In [27]:
df.describe().T

   count      mean       std       min       25%       50%       75%       max
A    6.0  0.784028  1.080856 -0.218940  0.136867  0.395667  1.138297  2.695336
B    6.0 -0.108440  0.453613 -0.691832 -0.405351 -0.105310  0.110262  0.575059
C    6.0  0.093414  0.655444 -0.907333 -0.252940  0.175690  0.479426  0.931581
D    6.0  0.733372  0.783741 -0.520709  0.371534  0.825355  1.328628  1.553583

In [28]:
# extract all the average values from all columns

df.describe().T['mean']

A    0.784028
B   -0.108440
C    0.093414
D    0.733372
Name: mean, dtype: float64

Sotring by an axis

In [29]:
df.sort_index(axis=0, ascending=False) # values inside index sorted

                   A         B         C         D
2013-01-06  1.378072 -0.691832  0.347157  1.553583
2013-01-05  2.695336 -0.458856  0.931581  0.236730
2013-01-04 -0.218940  0.575059  0.523515 -0.520709
2013-01-03  0.058369  0.034216 -0.907333  0.775947
2013-01-02  0.372361 -0.244836  0.004223  1.479917
2013-01-01  0.418973  0.135611 -0.338661  0.874763

In [30]:
df.sort_index(axis=1, ascending=False) # COLUMNS should be sorted, Not the index time stamps!

                   D         C         B         A
2013-01-01  0.874763 -0.338661  0.135611  0.418973
2013-01-02  1.479917  0.004223 -0.244836  0.372361
2013-01-03  0.775947 -0.907333  0.034216  0.058369
2013-01-04 -0.520709  0.523515  0.575059 -0.218940
2013-01-05  0.236730  0.931581 -0.458856  2.695336
2013-01-06  1.553583  0.347157 -0.691832  1.378072

Sotring by values

In [31]:
df.sort_values( by='B')

                   A         B         C         D
2013-01-06  1.378072 -0.691832  0.347157  1.553583
2013-01-05  2.695336 -0.458856  0.931581  0.236730
2013-01-02  0.372361 -0.244836  0.004223  1.479917
2013-01-03  0.058369  0.034216 -0.907333  0.775947
2013-01-01  0.418973  0.135611 -0.338661  0.874763
2013-01-04 -0.218940  0.575059  0.523515 -0.520709

## Selection

### Getting

Selecting a single column, which yields a `Series`, equivalent to `df.A`

In [70]:
#df[['A','C']] # SELECTION OF COLUMN is the default value for selection
df['A']

0    foo
1    bar
2    foo
3    bar
4    foo
5    bar
6    foo
7    bar
Name: A, dtype: object

Selecting via [ ], which slice the rows

In [33]:
df[0:2] # [from, to) [ means include, ) means exclude

# 0, 1 is included, 2 is excluded

                   A         B         C         D
2013-01-01  0.418973  0.135611 -0.338661  0.874763
2013-01-02  0.372361 -0.244836  0.004223  1.479917

In [71]:
df[-3:-1]

     A    B         C         D
5  bar  two  0.361361  2.176346
6  foo  one  0.438001 -1.800983

### Selection by label

For getting a cross section using a label

In [35]:
dates[0]

Timestamp('2013-01-01 00:00:00')

In [36]:
df.loc[dates[0]]

A    0.418973
B    0.135611
C   -0.338661
D    0.874763
Name: 2013-01-01 00:00:00, dtype: float64

Selection on a multi-axis by label

In [37]:
df.loc['2013-01-01':'2013-01-03', ['A', 'B']]

                   A         B
2013-01-01  0.418973  0.135611
2013-01-02  0.372361 -0.244836
2013-01-03  0.058369  0.034216

In [38]:
df.loc[:, ['A', 'B']] # : means select * or everything!

# dataframe.loc [ row selection, column selection]

                   A         B
2013-01-01  0.418973  0.135611
2013-01-02  0.372361 -0.244836
2013-01-03  0.058369  0.034216
2013-01-04 -0.218940  0.575059
2013-01-05  2.695336 -0.458856
2013-01-06  1.378072 -0.691832

### Selection by position

In [39]:
df.iloc[3]

A   -0.218940
B    0.575059
C    0.523515
D   -0.520709
Name: 2013-01-04 00:00:00, dtype: float64

By integer slices, acting similar to numpy/python

In [40]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04 -0.218940  0.575059
2013-01-05  2.695336 -0.458856

For slicing rows explicitly

In [41]:
df.iloc[1:3, :]

                   A         B         C         D
2013-01-02  0.372361 -0.244836  0.004223  1.479917
2013-01-03  0.058369  0.034216 -0.907333  0.775947

For slicing columns explicitly

In [42]:
df.iloc[:, 1:3]

                   B         C
2013-01-01  0.135611 -0.338661
2013-01-02 -0.244836  0.004223
2013-01-03  0.034216 -0.907333
2013-01-04  0.575059  0.523515
2013-01-05 -0.458856  0.931581
2013-01-06 -0.691832  0.347157

### Boolean indexing

using a single column's values to select data

In [43]:
df[df['A'] > 0]

                   A         B         C         D
2013-01-01  0.418973  0.135611 -0.338661  0.874763
2013-01-02  0.372361 -0.244836  0.004223  1.479917
2013-01-03  0.058369  0.034216 -0.907333  0.775947
2013-01-05  2.695336 -0.458856  0.931581  0.236730
2013-01-06  1.378072 -0.691832  0.347157  1.553583

In [44]:
df[df['A'] > 0]['B'] # Filter from 1 column and apply changes to another column

# filter was applied on A, and then corresponding B values were printed

2013-01-01    0.135611
2013-01-02   -0.244836
2013-01-03    0.034216
2013-01-05   -0.458856
2013-01-06   -0.691832
Name: B, dtype: float64

Selecting values from a DataFrame where a boolean condition is met

In [45]:
df[df > 0]

                   A         B         C         D
2013-01-01  0.418973  0.135611       NaN  0.874763
2013-01-02  0.372361       NaN  0.004223  1.479917
2013-01-03  0.058369  0.034216       NaN  0.775947
2013-01-04       NaN  0.575059  0.523515       NaN
2013-01-05  2.695336       NaN  0.931581  0.236730
2013-01-06  1.378072       NaN  0.347157  1.553583

using `isin()` method for filtering

In [73]:
df2 = df.copy() # Creates a DEEP COPY
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three','four', 'three']

df2

     A      B         C         D      E
0  foo    one -0.534214 -0.191460    one
1  bar    one  1.335797  1.933895    one
2  foo    two -0.131242 -0.162023    two
3  bar  three  0.054219  0.529135  three
4  foo    two -0.100325  0.150139   four
5  bar    two  0.361361  2.176346  three
6  foo    one  0.438001 -1.800983   four
7  bar  three  0.361923  0.316449  three

In [74]:
df2[df2['E'].isin(['two', 'four'])]

     A    B         C         D     E
2  foo  two -0.131242 -0.162023   two
4  foo  two -0.100325  0.150139  four
6  foo  one  0.438001 -1.800983  four

## Missing data

pandas primarily uses the `np.nan` to represent missing data. It is by default not inclued in a computations.
Reindexing allows you to change/add/delete the index on a special axis. This return a copy of data.

In [48]:
df1 = df.reindex(index = dates[0:4], columns = list(df.columns) + ['E'])
df1.loc[dates[0] : dates[1], 'E'] = 1
df1

                   A         B         C         D    E
2013-01-01  0.418973  0.135611 -0.338661  0.874763  1.0
2013-01-02  0.372361 -0.244836  0.004223  1.479917  1.0
2013-01-03  0.058369  0.034216 -0.907333  0.775947  NaN
2013-01-04 -0.218940  0.575059  0.523515 -0.520709  NaN

Top drop any rows that have missing data.

In [49]:
df1.dropna(how='any')

                   A         B         C         D    E
2013-01-01  0.418973  0.135611 -0.338661  0.874763  1.0
2013-01-02  0.372361 -0.244836  0.004223  1.479917  1.0

In [50]:
df1.dropna(axis=1)

                   A         B         C         D
2013-01-01  0.418973  0.135611 -0.338661  0.874763
2013-01-02  0.372361 -0.244836  0.004223  1.479917
2013-01-03  0.058369  0.034216 -0.907333  0.775947
2013-01-04 -0.218940  0.575059  0.523515 -0.520709

In [51]:
df1.dropna(axis=0)

                   A         B         C         D    E
2013-01-01  0.418973  0.135611 -0.338661  0.874763  1.0
2013-01-02  0.372361 -0.244836  0.004223  1.479917  1.0

Filling missing data.

In [52]:
df1.fillna(value=5) # np.nan, None, NULL, null

                   A         B         C         D    E
2013-01-01  0.418973  0.135611 -0.338661  0.874763  1.0
2013-01-02  0.372361 -0.244836  0.004223  1.479917  1.0
2013-01-03  0.058369  0.034216 -0.907333  0.775947  5.0
2013-01-04 -0.218940  0.575059  0.523515 -0.520709  5.0

To get the boolean mask where values are `nan`

In [53]:
pd.isna(df)

                A      B      C      D
2013-01-01  False  False  False  False
2013-01-02  False  False  False  False
2013-01-03  False  False  False  False
2013-01-04  False  False  False  False
2013-01-05  False  False  False  False
2013-01-06  False  False  False  False

## Operations

Operations in general exclude missing data.
Performing a descriptive statistic:

In [54]:
df.mean()

A    0.784028
B   -0.108440
C    0.093414
D    0.733372
dtype: float64

Same operation on the other axis:

In [55]:
df.mean(1)

2013-01-01    0.272672
2013-01-02    0.402916
2013-01-03   -0.009700
2013-01-04    0.089731
2013-01-05    0.851198
2013-01-06    0.646745
Freq: D, dtype: float64

Operating with objects that have different dimensionality and need alignment. In addition, pandas automatically
broadcasts along the specified dimension

In [56]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index = dates).shift(2)
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [57]:
df.sub(s, axis='index')

                   A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02       NaN       NaN       NaN       NaN
2013-01-03 -0.941631 -0.965784 -1.907333 -0.224053
2013-01-04 -3.218940 -2.424941 -2.476485 -3.520709
2013-01-05 -2.304664 -5.458856 -4.068419 -4.763270
2013-01-06       NaN       NaN       NaN       NaN

## Merge

pandas provide various faciliteis for easily combining together Series and DataFrame objects with various kinds of set logic for the indees and relational algebra functionality in the case of join/ merge-type operations.

Concatenating pandas objects together with concat()

In [58]:
df = pd.DataFrame(np.random.randn(10, 4))
df

          0         1         2         3
0  0.323139  1.260437  1.545700 -0.527818
1 -0.913311 -1.628591  0.583153 -1.089951
2 -0.478578 -0.102416  0.982257 -1.804713
3 -0.315962  1.019574 -0.437218 -0.797544
4 -2.557698 -0.344971 -0.318080  1.554736
5 -0.118729  1.311982 -0.592257 -1.273082
6 -1.142794 -0.009231 -0.730299 -1.607729
7  1.266908  0.743079  1.128066 -0.064119
8 -0.447481 -0.028482 -0.277885  0.716713
9  0.016442  0.962272  0.382930  0.851256

In [59]:
# break it onto pieces
pieces = [df[:3], df[3:7], df[7:]]

pd.concat(pieces)

          0         1         2         3
0  0.323139  1.260437  1.545700 -0.527818
1 -0.913311 -1.628591  0.583153 -1.089951
2 -0.478578 -0.102416  0.982257 -1.804713
3 -0.315962  1.019574 -0.437218 -0.797544
4 -2.557698 -0.344971 -0.318080  1.554736
5 -0.118729  1.311982 -0.592257 -1.273082
6 -1.142794 -0.009231 -0.730299 -1.607729
7  1.266908  0.743079  1.128066 -0.064119
8 -0.447481 -0.028482 -0.277885  0.716713
9  0.016442  0.962272  0.382930  0.851256

Adding a column to a `DataFrame` is relatively fast. However adding a row requires a copy, and may be expensive. It is recorecommended passing a pre-build list of records to the `DataFrame` constructor instead of buildinga `DataFrame` by iteratively appending records to it.

### Join
SQL style merges

In [60]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval' : [1, 2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})

left

   key  lval
0  foo     1
1  foo     2

In [61]:
right

   key  rval
0  foo     4
1  foo     5

In [62]:
pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

## Grouping

By 'group by' we are referring to a process invloving one or more of the following steps:


*   **Splitting** the data into group base on some criteria
*   **Applying** a function to each group independently

*   **Combining** the results into a data structure

In [63]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
                         'foo', 'bar', 'foo', 'bar'],
                   'B': ['one', 'one', 'two', 'three',
                         'two', 'two', 'one', 'three'],
                   'C': np.random.randn(8),
                   'D': np.random.randn(8)})
df

     A      B         C         D
0  foo    one -0.534214 -0.191460
1  bar    one  1.335797  1.933895
2  foo    two -0.131242 -0.162023
3  bar  three  0.054219  0.529135
4  foo    two -0.100325  0.150139
5  bar    two  0.361361  2.176346
6  foo    one  0.438001 -1.800983
7  bar  three  0.361923  0.316449

Grouping and then applying the `sum()` funcion to the resuling group

In [64]:
df.groupby('A').sum()

                    B         C         D
A
bar  onethreetwothree  2.113299  4.955826
foo      onetwotwoone -0.327780 -2.004327

Grouping by multiple columns forms a hierarchical index, and again we can apply the sum() function

In [65]:
dir(df)

['A',
 'B',
 'C',
 'D',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bigquery',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_geometry',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [66]:
df.groupby(['A', 'B']).sum()

                  C         D
A   B
bar one    1.335797  1.933895
    three  0.416141  0.845584
    two    0.361361  2.176346
foo one   -0.096213 -1.992443
    two   -0.231567 -0.011884